### ISSUE TITLE
Datasets link 

### ISSUE THREAD

**Issue by ajay-yug** [pedrodiamel/ferattention#2]
Hi, 
Would you be able to provide link of datasets used to train.
Thank you.

**Comment by onwaiers** [comment]
Can you provide the link of  datasets used to train

**Comment by djovanoski** [comment]
@cs12b033 @onwaiers any update on this issue on your side because as i see from Sep/Nov 2019 there is no answer on your questions?

**Comment by pedrodiamel** [comment]
Hello @cs12b033 
http://mohammadmahoor.com/affectnet/

For preprocessing dataset:
https://github.com/pedrodiamel/ferattention/blob/master/scripts/create_data_dark.py
